services:
  source:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_HTTP_PORT: ${INFLUXDB_HTTP_PORT}
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_RETENTION}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUXD_LOG_LEVEL: ${INFLUXD_LOG_LEVEL}
    ports:
      - 1234:8086
    volumes:
      - influxdb-source:/var/lib/influxdb2
      - ./test/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - test


  target:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_HTTP_PORT: ${INFLUXDB_HTTP_PORT}
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_RETENTION}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUXD_LOG_LEVEL: ${INFLUXD_LOG_LEVEL}
    ports:
      - 1235:8086
    volumes:
      - influxdb-target:/var/lib/influxdb2  
    networks:
      - test


  backup:
    build: 
      context: .
      dockerfile: Dockerfile
    command: backup
    volumes:
      - ./test/temp/current:/backups/current
      - ./test/temp/archive:/backups/archive
    environment:
       INFLUX_HOST: http://source:${INFLUXDB_HTTP_PORT}
       INFLUX_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    networks:
      - test


  restore:
    build: 
      context: .
      dockerfile: Dockerfile
    command: restore
    volumes:
      - influxdb-backup-current:/backups/current
      - influxdb-backup-archive:/backups/archive
    environment:
       INFLUX_HOST: http://target:${INFLUXDB_HTTP_PORT}
       INFLUX_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    networks:
      - test



volumes:
  influxdb-source:
  influxdb-target:
  influxdb-backup-current:
  influxdb-backup-archive:

networks:
  test: