name: Test, Build, 

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  # Job 1: Test Bash Script
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup InfluxDB
        uses: RasmusLar/influxdb-action@v6
        with:
            influxdb_version: latest
            influxdb_start: false      
        
      - name: Execute Test Bash Script
        run: |
          chmod +x ./test/run-test.sh  
          cd ./test
          ./run-test.sh  # Führt das Bash-Skript aus
          
      - name: Check if script succeeded
        run: echo "Bash script executed successfully!"



# Job 2: Build Multi-Platform Docker Image
  build-push:
    runs-on: ubuntu-latest
    needs: test  # Dieser Job wird nur ausgeführt, wenn der 'test'-Job erfolgreich war

    steps:
        - name: Checkout code
          uses: actions/checkout@v4  

        # Setup Docker Buildx für Multi-Plattform Builds
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Build
          uses: docker/build-push-action@v6
          with:
            platforms: linux/amd64, linux/arm64,
            push: true
            tags: ghcr.io/rliegmann/influxdb-backup:latest
        